toolchain_path: "/Library/Developer/Toolchains/swift-latest/usr/lib/swift/macosx/"

name: SwiftTensorflow
options:
  bundleIdPrefix: com.swiftTensorflow

targets:
  SwiftTensorflow:
    type: tool
    platform: macOS
    deploymentTarget: "10.13"
    sources: 
        - Sources
    dependencies:
      - framework: ${ toolchain_path }/libtensorflow_framework.so
      - framework: ${ toolchain_path }/libtensorflow.so
      - framework: libpython2.7.tbd
    settings:
      SWIFT_OPTIMIZATION_LEVEL: -O
      LD_RUNPATH_SEARCH_PATHS: ${ toolchain_path }
      OTHER_LDFLAGS:  -lpython
    
